### PR TITLE
incorrect api call

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
```
    def __init__(self, robot, entityDes, objectIDsDes=None, searchArea="on_top_of", navigation_area=""):
        """ Constructor

        :param robot: robot object
        :param entityDes: EdEntityDesignator indicating the (furniture) object to inspect
        :param objectIDsDes: designator that is used to store the segmented objects
        :param searchArea: string defining where the objects are w.r.t. the entity, default = on_top_of
        :param navigation_area: string identifying the inspection area. If provided, NavigateToSymbolic is used.
        If left empty, NavigateToObserve is used.
        """
```

### CODE REVIEW

**Comment by rokusottervanger** [comment]
I agree that this is a bug, but does this fix result in the desired behavior? (honest question) This should be tested with any type of object one may want to inspect. That definitely includes a piece of furniture with some area, but maybe also a room (?). Did you test if this fix gives the desired behavior?

**Comment by MatthijsBurgh** [comment]
At least it is not broken anymore. I don't think it should inspect a room, maybe all objects in a room. But Inspect is just segmentation, which can not be done with rooms.

**Comment by MatthijsBurgh** [comment]
It's old behavior is recovered by this fix.

**Comment by rokusottervanger** [comment]
Inspect is not just segmentation, it also includes navigation and adjusting
the pose. But if the old behavior is recovered, that sounds good for now.

**Pull request merged**
