### PR TITLE
save variable before accesing "p"

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Sorry commit is by me. I was not expecting to be any other gitsu user than me on this laptop.

**Comment by LoyVanBeek** [comment]
For reference: this solves vary nasty https://github.com/tue-robotics/tue_robocup/issues/348

**Comment by rokusottervanger** [comment]
Good catch, @MatthijsBurgh!

**Comment by MatthijsBurgh** [comment]
Thanks @rokusottervanger

**Pull request merged**
